### ISSUE TITLE
Tracking issue: additional mining page content

### ISSUE THREAD

**Issue by har00ga** [filecoin-project/filecoin-docs#102]
Related to #98 

Below is a personal todo for further expansion of the mining page. I will reference individual PRs solving these as I progress. To reviewers, feel free to reply with anything else that should be included. 

Additional sections:
- [x]   Coming from another ecosystem?
- [x]   Aren't these requirements comparatively high?
- [x]   post check

All about deals
- [x]   background and ask process - **need info**

Getting rewards
- [ ]   checking rewards - **need info**
- [ ]   withdrawal instructions

Uptime, slashing and penalties
- [x]   intro and links, slashing resources

**Comment by johnnymatthews** [comment]
Looks like #98 got merged. Can this be closed now @har00ga?

**Comment by har00ga** [comment]
Yep!
