### ISSUE TITLE
Add network info to docs site

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/filecoin-docs#1054]
Move the static content of network info to docs page.

Find a better home for  https://docs.filecoin.io/reference/#networks  so its easier to find, would be nice if we can improve the SEO of it too

**Comment by johnnymatthews** [comment]
## Tasks

- [ ] Remove the out-bound link to network.filecoin.io from sidebar nav.
- [ ] Create a standalone page called **Networks** somewhere. Likely in the **About Filecoin** section.
- [ ] Grab the static info for each network from [network.filecoin.io](https://network.filecoin.io/).
- [ ] Mention that Nerpanet was deprecated on 2021-09-16.
- [ ] Add some SEO friends words onto the page.
