### ISSUE TITLE
Move Lotus-specific docs to their own documentation repo and site.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1071]
It's time to move all the Lotus-related documentation into its own repo and its own documentation site. When the Filecoin network first went live in 2020, Lotus was the only stable implementation, so it made sense to couple the Filecoin docs _with_ the Lotus docs. However, more Filecoin implementations are becoming stable, so we need to move Lotus documentation into its own repo and website. This issue can be used to track child issues for this project.

## Tasks

- [ ] Create a new repository for Lotus documentation.
- [ ] Create a site for Lotus docs to use.
- [ ] Go through each section in Filecoin docs and list which pages/sections need to be lifted out:
    - [ ] About Filecoin
    - [ ] Networks
    - [ ] Get Started
    - [ ] Store
    - [ ] Mine
    - [ ] Build
    - [ ] Reference

Further tasks will be added as this project progresses.
