### ISSUE TITLE
Replace "miner" with "storage provider" where possible.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1158]
The Filecoin project is moving away from using the term _miner_ and replacing it with _storage provider_, _retrieval provider_, or just _provider_. However, we need to make sure we're not changing anything within code blocks. We need the user to know certain cases where _miner_ refers to a direct variable, daemon, or function within a Filecoin implementation.

## Tasks

- [x] Find all instances of _miner_ outside of code blocks.
    - [x] In pages where we mention a miner daemon, call out why it's called _miner_.
- [ ] Update pages and links.
    - [x] Find page titles with _miner_ in them.
    - [x] Update page names to reflect the new naming convention.
    - [x] **HORRENDOUSLY IMPORTANT**: Update all links to those pages, so we don't break anything.
    - [x] **ALSO HORRENDOUSLY IMPORTANT**: Add redirects into `/docs/.vuepress/public/redirects`.
    - [x] Run a dead-link checker against a preview to make sure we've not broken anything.

### Nice to have, but not fully required

- [ ] Find any images with `miner` in the name, and rename them to fit the naming convention. 
    - [ ] Update any references to these images.

**Comment by johnnymatthews** [comment]
Pages:

- [ ] ./about-filecoin/faq.md
- [ ] ./about-filecoin/filecoin-compared-to.md
- [ ] ./about-filecoin/how-filecoin-works.md
- [ ] ./about-filecoin/ipfs-and-filecoin.md
- [ ] ./about-filecoin/what-is-filecoin.md
- [ ] ./about-filecoin/why-filecoin.md
- [ ] ./build/filecoin-pinning-services.md
- [ ] ./build/get-started.md
- [ ] ./build/local-devnet.md
- [ ] ./build/powergate.md
- [ ] ./community/contribute/grammar-formatting-and-style.md
- [ ] ./community/README.md
- [ ] ./get-started/README.md
- [ ] ./get-started/store-and-retrieve/lotus-only-retrieval.md
- [ ] ./get-started/store-and-retrieve/README.md
- [ ] ./get-started/store-and-retrieve/retrieve-data.md
- [ ] ./get-started/store-and-retrieve/set-up.md
- [ ] ./get-started/store-and-retrieve/store-data.md
- [ ] ./mine/hardware-requirements.md
- [ ] ./mine/how-mining-works.md
- [ ] ./mine/mining-architectures.md
- [ ] ./mine/mining-rewards.md
- [ ] ./mine/slashing.md
- [ ] ./networks/network-performance.md
- [ ] ./networks/README.md
- [ ] ./reference/glossary.md
- [ ] ./reference/README.md
- [ ] ./software/README.md
- [ ] ./store/filecoin-plus.md
- [ ] ./store/README.md

**Comment by johnnymatthews** [comment]
Dead link checker on internal links came back with three errors. Fixes those. Links are now fine. Good to merge this one, apart from the search issue. I'm dealing with Algolia right now to try and get them to re-index the site sooner.

**Comment by johnnymatthews** [comment]
So the PR is ready to go. All the content has been updated, the pages have been renamed, and the links have been changed to go to the right places! But there's a problem...

The searchbar is powered by Algolia, which indexes the site once a week. Indexing isn't something we can control, as far as I know anyway. I've been crawling through my emails and Aloglia dashboard to see if there's anyway to prompt an early re-index, but I can't find anything.

Not being able to re-index the site is a problem because this PR moves a bunch of files around. This means that a user might be able to go to docs.filecoin.io, search for _Mine_, click the first result, and hit a 404. Hitting a 404 is a problem we can't control either, because VuePress handles 404 redirects client-side using funky JavaScript stuff, which loads _before_ Algolia does - esentially, our `/docs/.vuepress/public/_redirects` file won't help here.

With all that in mind, here's three solutions:

1. Fall back to the default VuePress search. This is an easy fix, and will mean this PR can land today. The search is slightly more limiting, as VuePress just looks for h1, h2, and h3 headers for content. But it works.
1. Focus on getting https://github.com/filecoin-project/filecoin-docs/pull/1162 working and cherry-pick the content updates into that. This is a decent solution, **but will take a few days**. Moving to the Doks theme is something that's gonna happen at some point anyway. But this solution will require a lot of my time, so Snap-deals documentation will have to sit on the back-burner until this is done. 
1. Merge this PR anyway and hope no one searches for _miner_ in the next few days. This is the easiest solution, but has a major potential for bad UX - at least until Algolia re-indexes the site, but I don't know when that's gonna be.

**Comment by johnnymatthews** [comment]
We ended up going with solution 1 - re-implement the VuePress default search.
