### ISSUE TITLE
Remove VuePress and use the Doks package.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1161]
Documentation sites maintained by Protocol Labs are being migrated to use the [Doks](getdoks.org) Hugo site package.

## Tasks

- [x] Move content over to Doks theme.
- [x] Update font to Filecoin docs default.\
- [x] Fill out the homepage.
- [x] Left nav fix (no menus on subpages)
- [x] Right nav fix (no "On this page" navigation)
- [x] Figure out dead nav items (some areas are blank, like Software -- should we just pull it?)
- [x] Figure out what do to with section index content (it currently shows up as sub-item because tier 1 nav links do not load pages on click)
- [x] Convert `:::tip` instances to use `alert` shortcode
- [x] Migrate links to be Hugonic and use `relref`
- [x] Lotus logos abound in `/static` directory
- [x] Allow sections in topbar nav.
- [x] Enable search across site.
- [x] Create sidebar menus for each topbar section. (as seen here: https://github.com/atwriter/new_doks_site/pull/1/commits/40e6eae81a8748645525afadf21b1759ce5f2c77)
    - [x] About Filecoin
    - [x] Networks
    - [x] Get started
    - [x] Store
    - [x] Storage provider
    - [x] Build
    - [x] Reference
- [x] Remove `{{ $frontmatter.title }}` and `{{ $frontmatter.description }}`
- [x] Replicate the docs.filecoin.io homepage.
- [x] Order the sidebar to fit docs.filecoin.io
- [ ] Move images back into [page bundles](https://gohugo.io/content-management/page-bundles/)
- [ ] Topbar logo should use sans-serif font. No idea where this times-new-roman has come from...
- [ ] Topbar nav should highlight which section we're in.
