### ISSUE TITLE
Split wallets up into hardware wallet support wallets, and community wallets.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1195]
We have lots of wallets listed in the [Manage FIL section](https://github.com/filecoin-project/filecoin-docs/blob/master/docs/about-filecoin/managing-assets.md). While this is great, we need to make it **very clear** that the wallets listed on the page are not supported by Filecoin in any way. The page could also use a bit of a clean up.

While there isn't a single solution supported by Filecoin, we highly recommend using a wallet with a hardware-wallet integration (Glif, for example).

## Tasks

- [x] Tell users we don't support any of these wallets.
- [x] Recommend that they use a wallet that comes with hardware-wallet integration.
- [x] Alphabetize the list of wallets.
- [x] Add a small section telling wallet creators how they can add their wallet to this list:
    - [x] Create an issue in Filecoin Docs with the name of the wallet and it's features.
    - [x] If the wallet is a mobile wallet, it must be available on both Android and iOS.
    - [x] The wallet must have been audited. The results of this audit must be public.

Eventually, it'd be nice to have a [Ethereum-style wallet picker](https://ethereum.org/en/wallets/find-wallet/), but that's a long way off yet.

**Comment by filwallet** [comment]
@johnnymatthews Hello, The FILWallet information has not been merged.

**Comment by Annamarie2019** [comment]
PR: [#1243](https://github.com/filecoin-project/filecoin-docs/pull/1243)

**Comment by johnnymatthews** [comment]
Closed in https://github.com/filecoin-project/filecoin-docs/pull/1243
