### ISSUE TITLE
Docs reorg - Developers section

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#1254]
This is a tracking issue for creating & reorganizing "Developers" section. It is a child of #1253.

### Section outline

- Developers
  - Getting started 
    - Hello World tutorial link
    - IPFS & Filecoin Application Design link
  - Overview 
    - What Filecoin brings to applications 
    - IPFS & Filecoin in application design
    - Using Filecoin in other chains (Polygon, Harmony, etc.)
  - Application data
    - NFT data: Use NFT.storage
    - General application data
      - Storage helpers: Web3.storage, Estuary, etc.
      - Manage your own storage deals with raw libraries: Textile Powergate (choose specific SPs, customize pricing, etc.)
    - Advanced application design: dbs, etc.
  - Build on Filecoin L1 (for wallets, exchanges, devtools)
    - Hello world tutorial (extremely simple version that uses a hosted node, something that can be completed in <15 mins)
    - Comprehensive tutorial (maybe point to longfei's Building with Filecoin API tutorial)
    - Signing libraries, devnets, hosted node providers

### Sub-tasks
- [ ] Write the content (use a Google Doc for faster editing) Issue #1262 
  - [ ] Overview
  - [ ] Application data
  - [ ] Build on Filecoin L1
- [ ] Create a PR to the `feat/developers-section-reorg` branch that stubs out the new structure. New top-level section called "Developers" & subsections as described in this issue. Issue #1263
- [ ] PR for each subsection (Overview, Application data, etc.) to `feat/developers-section-reorg` branch Issue #1264
- [ ] Incorporate or delete existing "Build" section content Issue #1265
- [ ] Merge into `main` branch Issue #1266

**Comment by mishmosh** [comment]
@johnnymatthews @jenksguo @dawnkelly09 please take a look and LMK if this general approach makes sense.

**Comment by dawnkelly09** [comment]
Looks good to me.

**Comment by johnnymatthews** [comment]
Looks good. I think we might want to add a section about Super Large Data (terabytes worth). Storing this much data isn't gonna apply to most devs, but it might get them excited if they see that they _can_ store loads of data.

**Comment by mishmosh** [comment]
Ah, and then point them to the Store > Very Large Data section?

**Comment by jenks-guo-filecoin** [comment]
> @johnnymatthews @jenks-guo-filecoin @dawnkelly09 please take a look and LMK if this general approach makes sense.

Thanks @mishmosh this looks great! 

Structurally I have only two inputs: 
1. This might be a bit opinionated. "Application data" sounds like storage + database but we don't yet have a database solutions. Would the word "Application storage be a better substitute? So basically where we say "data" in the navigation/title, we change them to storage and in the page we can use file storage/storage/data interchangeably.

I am keen to hear from @johnnymatthews on this choice of word. 

2. Developers are usually short on time. I the past, a Getting Started top nav under "Developers" will do very well, and can act as jump board to other areas. I would like to add a "Getting Started" area and then list a few link there that links to "Hello world tutorial" and "IPFS & Filecoin Application Design". For a first iteration, we could just link Developers -> Getting Started directly to "Hello world tutorial", so a fast link to tutorial for the impatient devs. :-D

**Comment by dawnkelly09** [comment]
> Looks good. I think we might want to add a section about Super Large Data (terabytes worth). Storing this much data isn't gonna apply to most devs, but it might get them excited if they see that they _can_ store loads of data.

Is this to be a separate section on the same level as Overview, Application data, etc? If so, I will add and create a corresponding issue.

**Comment by mishmosh** [comment]
> 1. "Application data" sounds like storage + database but we don't yet have a database solutions. Would the word "Application storage be a better substitute? So basically where we say "data" in the navigation/title, we change them to storage and in the page we can use file storage/storage/data interchangeably.

Interesting idea, let's see how it works during the course of writing #1262.

> 2. Developers are usually short on time. I the past, a Getting Started top nav under "Developers" will do very well, and can act as jump board to other areas. I would like to add a "Getting Started" area and then list a few link there that links to "Hello world tutorial" and "IPFS & Filecoin Application Design". For a first iteration, we could just link Developers -> Getting Started directly to "Hello world tutorial", so a fast link to tutorial for the impatient devs. :-D

The problem with jumping too quickly to a "Hello world"-type tutorial (especially the one in the Filecoin L1 section) is that most devs coming to the docs don't need to build on L1. Let's stick to 1 initial section (whether it's called Getting Started or Overview is probably a judgment call); we can introduce the tutorial links fairly early on but after we've helped people understand & choose between using a storage helper vs. building directly on Filecoin L1.

**Comment by johnnymatthews** [comment]
Closed in https://github.com/filecoin-project/filecoin-docs/pull/1484.
