### ISSUE TITLE
Powergate CLI - cannot use quic-go doesn't build on Go 1.18 yet

### ISSUE THREAD

**Issue by jsolly** [filecoin-project/filecoin-docs#1355]
### Context 
I followed the [Powergate doc page](https://github.com/filecoin-project/filecoin-docs/blob/main/content/en/build/powergate.md) to install the CLI, but I am running into errors.

#### First Error
```shell
$ git clone https://github.com/textileio/powergate
$ cd powergate
$ make install-pow
```
`make: go: Command not found`

I Googled that error,  and it looks like I need to install Go on my Mac. I followed the instructions on the [Go install page](https://go.dev/doc/install) and installed go 1.19 (latest)

#### Second Error
I tried `make install-pow` again and got a different error

`cannot use "quic-go doesn't build on Go 1.18 yet.`

I found that [one of your workflows](https://github.com/textileio/powergate/commit/eab2f94897db3dc567b9292ada5e71a9558c476b) uses Go 1.17, so I installed Go 1.17.13

I tried to make install again and I didn't see any errors
```shell
🍁johnsolly:22-08-17:powergate $ make install-pow
CGO_ENABLED=0 go install -ldflags="-X github.com/textileio/powergate/v2/buildinfo.BuildDate=2022-08-17T19:28:12Z -X github.com/textileio/powergate/v2/buildinfo.GitCommit=b82b011 -X github.com/textileio/powergate/v2/buildinfo.GitBranch=master -X github.com/textileio/powergate/v2/buildinfo.GitState=clean -X github.com/textileio/powergate/v2/buildinfo.GitSummary=v2.6.2-6-gb82b011 -X github.com/textileio/powergate/v2/buildinfo.Version=git" ./cmd/pow
```

#### Third issue, cannot find `pow`
I tried:
```shell
pow -h
```
But I am getting an error that 'pow' cannot be found. In my experience, this means I need to add something to PATH so it can be recognized. How can I get `pow` working in the MacOS terminal?

### Discussion
What is the recommended version of Go for Powergate CLI?
Are there any other dependencies I need to use Powergate CLI?
Once I get this info, I am happy to help write the docs on it.

I am brand new to filecoin and don't have any experience with Go.

### Environment
I ran these commands today (8/17/22). According to the [Git Repo](https://github.com/textileio/powergate) I am using version 2.6.2
MacOS 12.5, Mac Mini (2018) with Intel CPU

**Comment by johnnymatthews** [comment]
[Textile](https://textile.notion.site/Our-mission-is-to-accelerate-the-exchange-of-information-across-society-f49e389e12e14473a3475e755a8d9cd6) created Powergate [and has its own repo](https://github.com/textileio/powergate). However, judging from the issues listed there, it looks like [you're not the only one experiencing problems with pow](https://github.com/textileio/powergate/issues/882). We'll do some digging on our side to see if we can figure out what's going on. If you need a quick response, you're better off raising this issue within the [Powergate repo](https://github.com/textileio/powergate). I hope this is a simple out-of-date dependency issue, but I might be wrong.

**Comment by jsolly** [comment]
Thank you so much @johnnymatthews! I read that repo's readme and I just needed to run these commands to set the PATH variables.
```shell
$ export PATH=$PATH:$(go env GOPATH)/bin
$ export GOPATH=$(go env GOPATH)
```
Now I can run `pow` ! Closing this issue now.

**Comment by johnnymatthews** [comment]
Oh perfect! In that case, we should add those vars into the tutorial!

## Tasks

- [ ] Add these vars into the Powergate tutorial (see @jsolly's [comment for details](https://github.com/filecoin-project/filecoin-docs/issues/1355#issuecomment-1218476773):
    - [ ] `export PATH=$PATH:$(go env GOPATH)/bin`
    - [ ] `export GOPATH=$(go env GOPATH)`

I'm gonna re-open this issue until we get this sorted. @jsolly feel free to stop following this issue if you want :)

**Comment by jsolly** [comment]
@johnnymatthews feel free to assign me this issue, too.

**Comment by johnnymatthews** [comment]
Done!

**Comment by jsolly** [comment]
Fixed in https://github.com/filecoin-project/filecoin-docs/pull/1361
