### ISSUE TITLE
How to connect to different networks.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1475]
We currently have a bunch of information on networks scattered around this repo. However, we don't have any specific information on how developers can switch between the three networks:

- Mainnet
- Wallaby testnet
- Hyperspace testnet

## Tasks

- [ ] Create a page, or a section in an existing page detailing:
    - [ ] The different networks available
    - [ ] What makes each network unique -- the use-case of each network
    - [ ] A simple Curl example for interacting with each network.
