### ISSUE TITLE
Migrate Boost docs into this repo.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1510]
The [Filecoin Boost docs exist](https://boost.filecoin.io/). They need to be migrated into this repo.

## Tasks

- [x] Create working branch: https://github.com/filecoin-project/filecoin-docs/tree/feat/add-boost-docs
- [x] Create placeholder pages.
- [x] Update relref link conflicts.
- [x] Add proper weight to each page.
- [x] Edit capitalization of titles.
- [x] Migrate content into pages.

Further tasks from @smagdali:

- [x] fix relref links in ‘migrate’ section
- [x] What's the correct way to rename a misnamed folder in Hugo? - migrate-a-monolith-lotus-mine**R**-to-boost
- [x] should we remove/update references to rollback, given that rollback won't be possible soon?
- [x] review and update linkTitles
- [x] remove the migration section ‘overview’
- [ ] Review all remaining 'STEF' comments and fix accordingly (rest need Mayank help - wouldn't block deploy)
- [ ] Set up 301 redirects from existing site.
- [x] https://github.com/filecoin-project/filecoin-docs/issues/1558
- [x] double check page weights and sort order

**Comment by smagdali** [comment]
I've done some more sections, and checked in - We'll get more done today.

Some outstanding items before we can migrate
- [x] fix relref links in ‘migrate’ section
- [x ] remove ‘overview’ section in migrate.
- [ ] What's the correct way to rename a misnamed folder in Hugo? - migrate-a-monolith-lotus-mine**R**-to-boost
- [ ] should we remove/update references to rollback, given that rollback won't be possible soon?
- [ ] review and update linkTitles
- [x] remove the migration section ‘overview’
- [ ] Review all 'STEF' comments and fix accordingly
- [ ] Set up 301 redirects from existing site.

**Comment by johnnymatthews** [comment]
Nice! I've added those tasks to the top so everything's in one place.

**Comment by johnnymatthews** [comment]
Closing due to inactivity.
