### ISSUE TITLE
Improve the docs homepage by adding workflows and personas to the blocks.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1518]
The current Filecoin Docs homepage tells the user what Filecoin is, a few interesting features of Filecoin, and where the reader can find the Lotus Docs. This layout was _fine_ for an initial homepage, but we can do much better.

I propose that we treat this homepage as a way for users to navigate to certain parts of the documentation, depending on what they're trying to do:

- Just find out _what_ Filecoin is → go to [Basics/About section](https://docs.filecoin.io/about/basics/what-is-filecoin/).
- Build dapps and smart-contracts → go to [Developers Smart Contract](https://docs.filecoin.io/developers/smart-contracts/filecoin-virtual-machine/) section.
- Set up a storage provider → go to the [Providers section](https://docs.filecoin.io/storage-provider/basics/overview/).
- Store a bunch of data on Filecoin → go to the [Store section](https://docs.filecoin.io/store/overview/start-storing/).

## Tasks

- [ ] ~Check in with the community/Filecoin devs to see if these use cases fit what we're expecting to see.~ Bumped to `p1` by the FVM team. No time to check in with community.
- [x] Create a short paragraph for each use case.
- [x] Create a design to house each paragraph/block.
    - [x] Ensure it makes visual sense in a mobile view.
- [x] Add callout section towards the top of the page for hackathons/events/major updates.
- [ ] Optional: create visual aids/images for each use case.

**Comment by johnnymatthews** [comment]
As well as adding in sections for each use-case/persona, it'd be useful to have a _Recent updates_ or just _Updates_ section. This new section can tell readers what's changed in the docs recently, and what's happening in the wider Filecoin Network community. We can also add a _Recent Blog Posts_ section to highlight the latest posts in the [Filecoin Blog](https://filecoin.io/blog/).

**Comment by johnnymatthews** [comment]
Bumping to P1 at the request of the FVM team.
