### ISSUE TITLE
Add project blueprints into the docs for web3 devs.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1546]
The FVM UX team has created a few project blueprints. Web3 development teams to use these blueprints to bootstrap their project on the Filecoin Network.

Since these blueprints are going to be fairly evergreen, we should add them into the FIlecoin Docs, likely under the `/developers` section.

## Tasks

- [x] Create new section OR find an existing section that these blueprints can live in.
- [x] Stub out pages to see that sidebar items, and decide if the chosen section _works_.
- [x] Move content from Google Docs into markdown.
- [x] Move over images and optimize.
- [ ] Push everything.
