### ISSUE TITLE
How to Invoke a Contract

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1551]
We have pages for deploying a contract, but we don't have a guide on how to interact with a contract that is already deployed.

## Tasks

- [ ] List the different methods for invoking/calling a contract.
    - [ ] Detail step-by-step instructions on how to call a contract using each method.
- [ ] Change `draft` to `false`.
