### ISSUE TITLE
How the test a contract.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1552]
We have a draft page for testing a contract, but with no content. Showing users how to run basic tests against the contract would be incredibly useful, especially since actors and smart-contracts on the Filecoin network have some intricacies.

## Tasks

- [ ] Explain why testing contracts/actors is useful.
- [ ] List different options for testing.
- [ ] Change `draft` variable to `false`.

**Comment by johnnymatthews** [comment]
Tests are generally covered all over the place in Solidity docs. Doesn't make sense to duplicate here.
