### ISSUE TITLE
Update tutorials to point to Hyperspace instead of Wallaby.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1571]
The upcoming Hyperspace testnet is a long lived testnet where developers can experiment and play around with their apps/tools. This issue tracks the updating of tutorials and guides in this repo to advise readers to use the Hyperspace testnet.

This issue is related to https://github.com/filecoin-project/filecoin-docs/issues/1565.

## Tasks

- [x] Find all occurrences of wallaby/Wallaby.
- [x] Find and replace where possible.
- [x] Remove wallaby images. Replace later.
- [x] Add warnings/callouts to any content that specifically requires readers use the Wallaby testnet.

**Comment by johnnymatthews** [comment]
Here's all the instances of `wallaby`:

```
./networks/overview/available-networks/index.md:28:- [Wallaby](#wallaby), an early smart-contract and actor test network for bleeding edge [Filecoin Virtual Machine]({{< relref "filecoin-virtual-machine" >}}) deployments.
./networks/overview/available-networks/index.md:168:/dns4/de0.bootstrap.wallaby.network/tcp/1337/p2p/12D3KooWHAvUVk5XuxSwi2dNLWbTDDRSGeHxMuWdQ3SQpRuNHbLz
./networks/overview/available-networks/index.md:169:/dns4/de1.bootstrap.wallaby.network/tcp/1337/p2p/12D3KooWBRqtxhJCtiLmCwKgAQozJtdGinEDdJGoS5oHw7vCjMGc
./networks/overview/available-networks/index.md:170:/dns4/ca0.bootstrap.wallaby.network/tcp/1337/p2p/12D3KooWCApBpUk7EX9pmEfyky1gKC6N2KJ74S1AwFfvnkDqw3pK
./networks/overview/available-networks/index.md:171:/dns4/sg0.bootstrap.wallaby.network/tcp/1337/p2p/12D3KooWLnYqr4hRoNHBJQVXsFGkDoKuoVfw5R2ASw1bHzrWU5Px
./networks/overview/available-networks/index.md:188:### Wallaby
./networks/overview/available-networks/index.md:190:The Wallaby testnet is intended for early testing of new Filecoin Virtual Machine features as the FVM is being actively developed. It is usually reset weekly with a new FVM release.
./networks/overview/available-networks/index.md:194:Information for this networks changes frequently. Check out the [Testnet wallaby reposiotry for the most up-to-date information](https://github.com/filecoin-project/testnet-wallaby/).
./developers/smart-contracts/about/faqs/index.md:80:Not necessarily. You can use one of the two public Wallaby nodes:
./developers/smart-contracts/about/faqs/index.md:82:- [wallaby.node.glif.io](https://wallaby.node.glif.io/)
./developers/smart-contracts/about/faqs/index.md:83:- [api.zondax.ch/fil/node/wallaby/rpc/v0](https://api.zondax.ch/fil/node/wallaby/rpc/v0)
./developers/smart-contracts/about/faqs/index.md:85:### How do I install a node on the Wallaby testnet?
./developers/smart-contracts/about/faqs/index.md:87:Factor8, the team that runs the Wallaby testnet, has a [guide on how to spin up a Lotus node on the Wallaby testnet](https://kb.factor8.dev/docs/filecoin/testnets/wallaby).
./developers/smart-contracts/about/support/index.md:26:- [`#fil-net-wallaby-discuss`](https://filecoinproject.slack.com/archives/C03KGBTJ0BY)
./developers/smart-contracts/about/support/index.md:27:- [`#fil-net-wallaby-help`](https://filecoinproject.slack.com/archives/C03KGBVJCKG)
./developers/smart-contracts/quickstart/index.md:50:You may notice that we are currently connected to the **Ethereum Mainnet**. We need to point MetaMask to the Filecoin network, specifically the _Wallaby testnet_. We'll use a website called [chainlist.org](https://chainlist.org/) to give MetaMask the information it needs quickly.
./developers/smart-contracts/quickstart/index.md:57:1. Scroll down to find the **Filecoin -- Wallaby** testnet:
./developers/smart-contracts/quickstart/index.md:59:    ![Find the Filecoin Wallaby testnet in Chainlist.](chainlist-filecoin-wallaby.png)
./developers/smart-contracts/quickstart/index.md:65:1. Back on the Chainlist.org page, click the **Filecoin -- Wallaby** testnet connect button again.
./developers/smart-contracts/quickstart/index.md:74:1. Open MetaMask, and you should see that you're now on the Filecoin Wallaby testnet:
./developers/smart-contracts/quickstart/index.md:78:Nice! Now we've got the Filecoin Wallaby testnet set up within MetaMask. You'll notice that our MetaMask window shows `0 TFIL`. Test-filecoin (`TFIL`) is `FIL` that has no value in the _real world_, and developers use it for testing. We'll grab some `TFIL` next.
./developers/smart-contracts/quickstart/index.md:87:1. Go to [wallaby.network](https://wallaby.network/#faucet) and scrolldown to the **Faucet** section.
./developers/smart-contracts/how-tos/add-to-metamask/index.md:3:description: "MetaMask is a popular browser extension that allows users to interact with blockchain applications. This guide shows you how to integrate FIL into MetaMask using the Wallaby testnet."
./developers/smart-contracts/how-tos/add-to-metamask/index.md:4:lead: "MetaMask is a popular browser extension that allows users to interact with blockchain applications. This guide shows you how to integrate FIL into MetaMask using the Wallaby testnet."
./developers/smart-contracts/how-tos/add-to-metamask/index.md:27:1. Scroll down to find the **Filecoin -- Wallaby** testnet:
./developers/smart-contracts/how-tos/add-to-metamask/index.md:29:    ![](chainlist-filecoin-wallaby.png)
./developers/smart-contracts/how-tos/add-to-metamask/index.md:35:1. Back on the Chainlist.org page, click the **Filecoin -- Wallaby** testnet connect button again.
./developers/smart-contracts/how-tos/add-to-metamask/index.md:44:1. Open MetaMask, and you should see that you're now on the Filecoin Wallaby testnet:
./developers/smart-contracts/how-tos/add-to-metamask/index.md:52:If you can't or don't want to use Chainlist, you can add the Wallaby network to your MetaMask manually.
./developers/smart-contracts/how-tos/add-to-metamask/index.md:94:    | Network name | `Filecoin Wallaby` |
./developers/smart-contracts/how-tos/add-to-metamask/index.md:95:    | New RPC URL | `https://wallaby.node.glif.io/rpc/v0` |
./developers/smart-contracts/how-tos/add-to-metamask/index.md:101:    - Glif Explorer: `https://explorer.glif.io/?network=wallaby`
./developers/smart-contracts/how-tos/add-to-metamask/index.md:102:    - Filscan: `https://explorer.glif.io/?network=wallaby`
./developers/smart-contracts/how-tos/add-to-metamask/index.md:108:1. The Wallaby testnet should now be shown in your MetaMask window:
./developers/smart-contracts/how-tos/add-to-metamask/index.md:110:    ![](wallaby-network-added.png)
./developers/smart-contracts/how-tos/add-to-metamask/index.md:116:You can now add funds to this wallet by using the [Wallaby testnet faucet]({{< relref "use-a-faucet" >}}).
./developers/smart-contracts/how-tos/use-a-faucet/index.md:3:description: "Faucets can send you some test FIL so that you can explore and experiment with a Filecoin testnet without having to pay for anything. There are two faucets available, one for the Builder testnet (buildernet) and the Wallaby testnet."
./developers/smart-contracts/how-tos/use-a-faucet/index.md:4:lead: "Faucets can send you some test FIL so that you can explore and experiment with a Filecoin testnet without having to pay for anything. There are two faucets available, one for the Builder testnet (buildernet) and the Wallaby testnet."
./developers/smart-contracts/how-tos/use-a-faucet/index.md:21:Before we begin, you must have an address on the Wallaby testnet. Follow the [Add to MetaMask guide]({{< relref "add-to-metamask" >}}) if you don't have one yet.
./developers/smart-contracts/how-tos/use-a-faucet/index.md:27:## Wallaby testnet
./developers/smart-contracts/how-tos/use-a-faucet/index.md:34:1. Go to [wallaby.network](https://wallaby.network/#faucet) and scrolldown to the **Faucet** section.
./developers/smart-contracts/how-tos/deploy-a-contract/index.md:41:1. Select your network from the **Environment tab**. If you want to deploy your contract to the Wallaby testnet, follow the [Add to MetaMask guide]({{< relref "add-to-metamask" >}}):
./developers/smart-contracts/how-tos/deploy-a-contract/index.md:66:You should also have an address on the Filecoin Wallaby testnet. See the [Add to MetaMask page]({{< relref "add-to-metamask" >}}) for information on how to get an address. You also need test-FIL `tFIL` in your wallet. See the [Use a Faucet]({{< relref "use-a-faucet" >}}) page for information on how to get test funds.
./developers/infrastructure/networks/index.md:31:| [Wallaby testnet](#wallaby-testnet) | Testnet | Weekly | [`wallaby.network#faucet`](https://wallaby.network/#faucet)
./developers/infrastructure/networks/index.md:37:### Wallaby testnet
./developers/infrastructure/networks/index.md:39:The Wallaby testnet is a _bleeding-edge_ test network for the programmability features being developed for the FVM. You can deploy both WASM actors and EVM-compatible smart contracts to Wallaby. Wallaby is reset every week, making it unsuitable for long-term testing of applications. The purpose of Wallaby is to allow developers to quickly poke and prod at any new features released within the latest development builds of the FVM.
./developers/infrastructure/networks/index.md:41:The Wallaby test is intended to be used by:
./developers/infrastructure/networks/index.md:47:The Wallaby testnet is operated and maintained by [Factor8 Solutions](https://github.com/Factor8Solutions). You can find Wallaby-specific documentation written by Factor8 at [kb.factor8.dev/docs/filecoin/testnets/wallaby](https://kb.factor8.dev/docs/filecoin/testnets/wallaby).
./developers/infrastructure/networks/index.md:53:- [Glif](https://explorer.glif.io/actor/?network=wallaby)
./developers/reference/tools/index.md:36:- [Deploy an EVM smart contract to FVM (to testnet)](https://observablehq.com/@jimpick/fvm-actor-code-playground-erc20-sans-events-wallaby-testne?collection=@jimpick/filecoin-virtual-machine)
./developers/reference/tools/index.md:39:- [Connect your Metamask Wallet](https://yosephks.medium.com/adding-fvm-wallaby-testnet-to-metamask-f1adeb85c46a)
./developers/reference/tools/index.md:44:- [Glif](https://explorer.glif.io/actor/?network=wallaby)
./developers/reference/json-rpc/eth/index.md:26:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:54:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:116:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \    src/languages update/json-rpc-examples
./developers/reference/json-rpc/eth/index.md:155:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:192:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:212:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:248:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:295:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:344:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:379:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:415:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:705:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:731:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:768:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:800:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:826:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:853:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:885:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
./developers/reference/json-rpc/eth/index.md:912:curl --location --request POST 'https://wallaby.node.glif.io/rpc/v0' \
```
