### ISSUE TITLE
Add Intro to Filecoin piece.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1582]
The _Intro to Filecoin_ piece is a stand along introduction the FIlecoin network, it's underlying infrastructure, and how users can interact with it. It doesn't require any outside knowledge of blockchains, Protocol Labs, or anything fancy like that.

## Tasks

- [x] Get the [draft from Google Doc](https://docs.google.com/document/d/1LsbLzpOj_gmUKpHJkoDl-zQzxdqcV7JyjHV-WmMJcXA/edit).
- [ ] I'll run a grammar and spell check to make sure it fits Filecoin Docs guidelines.
- [x] Convert the whole thing to markdown.
- [ ] Check for formatting errors and add relevant front-matter.
- [ ] Prep PR and post a preview in fvm-core-team for team approval.
- [ ] Merge.

## Content tasks

- [ ] Remove [intro.filecoin.io](http://intro.filecoin.io/) title.
- [ ] Add redirect 

This needs to be done today -- hence the `p0`.
