### ISSUE TITLE
How to send FIL to MetaMask on mainnet.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1668]
The process for getting FIL on testnets is already well documented, however the process for Mainnet is going to be substantially similar. Either:

- Users have a friend send them FIL directly to their `f410` or eth `0x` address.
- Users buy FIL on an exchange, transfer from the exchange to a Glif wallet, and then send from the Glif wallet to an `f410` or eth `0x` address.

## Tasks

- [ ] Explain the process for the exchange path.
- [ ] Mention that user/friend path.
- [ ] Explain why users can't send directly from an exchange to an `f410` or eth `0x` address.
- [ ] Add exchange-specific details to the [Exchange integration page](https://docs.filecoin.io/reference/exchanges/exchange-integration/#accounts-and-wallets).

**Comment by ElPaisano** [comment]
Hey @johnnymatthews I can pick this one up as well if it isn't already being worked on?

**Comment by johnnymatthews** [comment]
Yeah @ElPaisano go ahead! Keep in mind that there is a project in the works to make this _very manual_ process a bit less manual. However, having both methods will still be useful.

**Comment by ElPaisano** [comment]
Addressed in https://github.com/filecoin-project/filecoin-docs/pull/1758

**Comment by trruckerfling** [comment]
@ElPaisano more context here as a similar ask on a diff board came in from product. will let you make the call on how to de-dupe and include any additional steps into what youre already working on. the write up below is pretty prescriptive, feel free to omit as needed

> Unlike Hyperspace, devs will have to buy / move FIL from another wallet / exchange and move it to Metamask.
> 
> This should assume they have Metamask set up an their 0x address handy.
> 
> Multiple scenarios need to be covered:
> 
> Moving FIL from an exchange to FVM
> 
> (Fallback option) If the exchange does not support f4 withdrawals or 0x withdrawals:
> - Buy FIL on an exchange
> - Set up a Glif wallet
> - Move it to a non-f4 address on Glif
> - Lookup the equivalent f4 address to your Metamask 0x address
> - Use Glif to send the funds to your Metamask address
> (Alternate 1 option) If the exchange supports f4 withdrawals (most likely will be the case for Coinbase at launch)
> - Lookup the equivalent f4 address to your Metamask 0x address
> - Send to f4 address directly from exchange
> (Alternate 2 option) If the exchange supports 0x withdrawals
> - Send to 0x address directly from exchange
> Moving FIL from a Glif wallet / Ledger wallet to your Filecoin wallet
> 
> Using a Metamask wallet (with Ledger support) for FVM directly
> 
> Note: This will require using the Ethereum app, not the Filecoin app, to sign transactions
> See more here: https://docs.google.com/document/d/1Zqk7EYgyIbrOGKyl2xL907maqoRA739MRChT91hylG4/edit#bookmark=id.bpujtscke2wb

**Comment by trruckerfling** [comment]
Suggest this is added to the mainnet quickstart and the quickstart page has 2 tabs - hyperspace and mainnet. aside from the differences in process to getting funds into your wallet, the process is largely the same. So mainnet tab, will explain the filforwarder and how that works.

**Comment by johnnymatthews** [comment]
Yeah that could work. Does that make sense @ElPaisano? Take a look at the [Run a local network](https://github.com/filecoin-project/filecoin-docs/blob/main/content/en/developers/infrastructure/how-tos/run-a-local-network/index.md#prerequisites) tutorial for an example on how tabs work.

**Comment by raulk** [comment]
Hm, I'll take a deeper look at this tomorrow, but the Quickstart should just operate on Hyperspace, and I think adding this content there would bloat the page. I would suggest a "Transferring FIL" page somewhere unrelated to Smart Contracts (Basics?), with a section for each route. I can help outline this tomorrow if that helps!

**Comment by trruckerfling** [comment]
subsumed into https://github.com/filecoin-project/filecoin-docs/issues/1770 FYI pls so you dont do duplicate work! @ElPaisano

**Comment by ElPaisano** [comment]
> subsumed into #1770 FYI pls so you dont do duplicate work! @ElPaisano

cheers closing this now
