### ISSUE TITLE
Explain what the FilFowarder is and how to use it.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1756]
The FilForwarder* is a smart-contract that lets users send FIL in the Ethereum address-space `f410...` to other address spaces like `f0`, `f1`, `f2`, or `f3`. The reasons why the contract needs to exist and the problems it solves can be found in the repo: https://github.com/lotus-web3/FilForwarder

* The name _FilForwarder_ will likely change in the near future.

## Tasks 

- [x] Explain what FilFowarder is.
    - [x] The problems that is solves.
    - [x] How it solves these problems.
- [ ] How to use it:
    - [x] Hardhat/contract method.
    - [ ] GUI method (currently being created by Glif.io.
