### ISSUE TITLE
Create `/basics/assets` section.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1827]
The `/smart-contracts/wallets` section is becoming a bit unruly. It's intended specifically for managing Wallets with Smart Contracts. However, it's evolved into _anything to do with FIL_. Basic FIL management (sending, transferring, etc) should be a basic section that all readers understand.

## Tasks

- [x] Create a **Assets** section under **Basics**.
- [x] Move anything to do with sending, transferring, or managing _just FIL_ into this new location.
- [ ] Anything that's to do with Wallet management + smart contracts, leave in `/smart-contracts/wallets`.

**Comment by mishmosh** [comment]
There's some good generic/intro content to Wallets that was lost in the latest docs reorg. Would be great to bring some of this back.

https://github.com/filecoin-project/filecoin-docs/pull/1252/files

**Comment by johnnymatthews** [comment]
> Would be great to bring some of this back.

This page has been added into PR #1828. [Here's a preview](https://bafybeico2plr6st4hgc2rbpon6axocz6eulftrbk2w6i7lz7syxpa4sbty.on.fleek.co/basics/assets/wallets/).
