### ISSUE TITLE
Prep `add/new-storage-provider-section` branch for merge.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1872]
The SP team have put together a super useful, if somewhat large, branch that adds in a bunch of Storage Provider information. The branch is `add/new-storage-provider-section`. This issue tracks the progress of reviewing that branch, and merging the contents into `main` safely.

## Tasks

- [x] Create PR for merge.
- [x] Fix merge conflicts.
- [ ] Assign items a menu to fall under.

**Comment by smagdali** [comment]
my notes and bugs spotted on: https://late-bird-3121.on.fleek.co/storage-provider/

1. remove Hardware, Rewards and Slashing
2. left nav is sorting alphabetically (is this the menu assignment task remaining?)
3. remove Angelo's new content until next week (I can't do a content pass today)
4. Is Filecoin deals the right heading for "Charging for Data and Auxilary Services, and Return-on-Investment"

**Comment by ivanka** [comment]
Please remove the inserted section 1: Prerequisites 

and revert to the submitted steps: 
1. Understand Filecoin economics
2. Plan your business
3. Make sure you have the right skills
4. Build the right infrastructure

**Comment by bobdubois** [comment]
couple things more:
- I undid Angelo's changes apart from some good points in the Sealing Pipeline page
- the "lead" text on every page is way too much text. A full paragraph should not go in the lead-in header.
- we agreed on PR's to edit content. I see major content changes directly committed.
- last-minute changes of this size are not a good idea

**Comment by bobdubois** [comment]
- Homepage (becoming a storage provider) restored in the format of Ivanka!
- video section is messy and has too much content that shouldn't go on the docs (like commercial material from other vendors)
