### ISSUE TITLE
Address lingering `todo` items within the Storage Provider section.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1892]
During the creation of the Storage Provider section, several todos were recorded within the markdown. Most of these todos were addresses before merging into `main`, however there were a few _non-blocking_ items that have yet to be seen to. This issue records each todo item. A subsequent PR will remove these todos from the markdown.

- [x] `.//architecture/lotus-components/index.md:43: Another important consideration is the size of the file system and available free space. Because the Filecoin chain grows every day<!--TODO NOBLOCK STEF by how much, currently, and how big is it? 04-02 I have asked around in slack -->, any available space will eventually fill up. Solutions like [SplitStore](https://lotus.filecoin.io/lotus/configure/splitstore/) and [compacting](https://lotus.filecoin.io/lotus/manage/chain-management/#compacting-the-chain-data) reduce the storage space used by the chain. Compacting involves replacing the built-up chain data with a recent lightweight snapshot.`
- [x] `.//filecoin-deals/storage-deals/index.md:32:<!-- TODO NOBLOCK STEF BOB feels like this section could be expanded. How do the markets work? what are the parameters of a deal? What's a good deal (for the client or for me. Who am I competing with? can we link out to something, or give it a page. -->`
- [x] `.//filecoin-deals/verified-deals/index.md:15:<!--TODO STEF BOB should this page be called Filecoin Plus, not Verified deals?-->`
- [x] `.//filecoin-deals/verified-deals/index.md:18:The goal of Filecoin is to be the decentralized storage network for humanity’s most important information. With that in mind, it is vital to onboard real and valuable data onto the network. Filecoin Plus (Fil+) is a social trust program that incentivizes Storage Providers to store that data in _verified deals_. A deal is _verified_ when the data owner (i.e. the client) undergoes a verification process, where a group of community _notaries_ judge the client and their particular usage of Filecoin to be useful or valuable in some way<!--TODO NOBLOCK STEF BOB how? -->. Notaries are responsible for asking questions to the client and conducting due diligence to build reasonable confidence in the trustworthiness of the client and their use case.`
- [x] `.//filecoin-deals/verified-deals/index.md:34:Getting a copy of the data requires systems and infrastructure to allow for large volumes, sometimes up to <!--TODO STEF BOB can we give a meaningful example here--> of data to be ingested into your system. This requires substantial internet bandwidth, with a minimum of 10Gb. However, many large Storage Providers use up to 100Gb internet connections. As an example, transferring 1 PiB of data takes XX hours on a 10Gb connection.`
- [x] `.//filecoin-deals/verified-deals/index.md:42:Tools and programs exist for this <!--TODO STEF what? --> to work but a Storage Provider needs to know how to operate this entire workflow. See [Filecoin Plus Programs]({{<relref "filecoin-programs" >}}) for more information on available programs. See [Architecture]({{<relref "lotus-components" >}}) for more information on the tooling and software components.`
- [x] `.//filecoin-deals/verified-deals/index.md:45:<!-- TODO NOBLOCK STEF BOB this section doesn't add much in the way of actionable specifics? delete?-->`
- [x] `.//skills/linux/index.md:32:Exclude the `nvidia-drivers` and `cuda` packages from your updates. <!--TODO NOBLOCK STEF BOB link to how - stef says actually I think this tip is really unhelpful unless we link to a tutorial on how these drivers are installed since they are not part of core Unbuntu https://linux.how2shout.com/how-to-install-cuda-on-ubuntu-20-04-lts-linux/ --> Once you have a working setup for your specific GPU, you won't want to risk breaking it without testing these packages first.`
- [x] `.//infrastructure/reference-architectures/index.md:126:The scratch space from PC1 is copied <!-- TODO BOB can you clarify - this means the data stored on the scratch, ie. that the scratch is shared? --> over to the PC2 worker. This PC2 worker also requires fast NVMe scratch space. Since we plan for 2 PC2 workers against 1 PC1 worker, the capacity of the scratch space per PC2 worker is half of the total scratch space capacity of the PC1 worker, 8TiB in our case.`
- [ ] `.//infrastructure/reference-architectures/index.md:132:TODO NOBLOCK ANGELO to write a section on the use of refurbished hardware`
- [x] `.//filecoin-economics/committed-capacity/index.md:26:Providing Committed Capacity is the easiest way to get started as a Storage Provider, but the economics are very dependent on the price of FIL. When the price of FIL is low, <!-- TODO NOBLOCK STEF BOB what is low? maybe give a dated example?--> it is not profitable to only provide Committed Capacity. This is where [Filecoin Plus]({{<relref "verified-deals" >}}) comes in along, with [extra services you can charge for]({{<relref "auxiliary-services" >}}).`
- [x] `.//filecoin-economics/storage-proving/index.md:23:The cryptographic challenge for storage proving is called _Window Proof-of-Spacetime_ (WindowPoSt). Storage Providers have a deadline of 30 minutes to respond to this WindowPoSt challenge via a message on the blockchain containing a [zk-SNARK](https://en.wikipedia.org/wiki/Zero-knowledge_proof) proof of the verified sector. Failure to submit this proof within the 30 minute deadline, or failure to submit it at all, results in _slashing_. Slashing means a portion of the [collateral]({{< relref "fil-collateral" >}}) will be forfeited <!-- TODO NOBLOCK STEF BOB where does it go? who gets my FIL? it's just burned, right --> and the _storage power_ of the Storage Provider gets reduced. Slashing is a way to penalize Storage Providers who fail to meet the agreed upon standards of storage.`
- [x] `.//filecoin-economics/storage-proving/index.md:25:<!-- TODO NOBLOCK STEF BOB a lot of duplication here with committed-capacity section -->`
- [ ] `.//filecoin-economics/slashing/index.md:23:<!--TODO NOBLOCK STEF BOB I think this page really needs an explanation of how the various penalties are calculated and applied-->`
- [x] `.//filecoin-economics/fil-collateral/index.md:22:To satisfy the multiple needs for collateral in a way that is minimally burdensome to Storage Providers, Filecoin includes three different collateral mechanisms: initial pledge collateral, block rewards as collateral, and storage deal provider collateral. The first is an initial commitment of Fil that a miner must provide with each sector. The second is a mechanism to reduce the initial token commitment by vesting block rewards over time. The third aligns incentives between Storage Provider and client, and can allow miners to differentiate themselves in the market. <!--TODO NOBLOCK STEF BOB needs more explanation or linking? is the second basically re-investing earned blocks to give greater future capacity?-->`
- [x] `.//filecoin-economics/fil-collateral/index.md:26:When a Storage Provider fails to answer to the WindowsPoSt challenges within the 30 minute deadline (see [Storage Proving]({{<relref storage-proving >}})), or when you take your storage offline and thereby break the rules of the storage deal, you will get penalized against the provided collateral. This penalty is called [_slashing_]({{<relref slashing>}}) and means that a portion of the pledged collateral is forfeited <!--TODO NOBLOCK STEF BOB where does it go? who gets it? Does it all go? -->and your storage power is reduced.`
- [x] `.//filecoin-economics/fil-collateral/index.md:46:The ecosystem does have [FIL Lenders](https://filecoin-lending.com/read-more) <!-- TODO NOBLOCK STEF BOB is this platform actually doing anything?--> who can provide you FIL (with interest) to get you started, which you can pay back over time and with the help of earned block rewards. Every lender, though, will still require you to supply up to 20% of the required collateral.`

**Comment by smagdali** [comment]
I've invited @bobdubois and @SgtCoin to this too. Some of these questions I don't know the answers to. 

except the first one- in March 2023, the chain is growing at ~50Gb/day

**Comment by SgtCoin** [comment]
I talked with a storage provider last week who said they see it fluctuate from ~20 GB a day to ~90 GB a day. Ill add some text to cover this based on ~50 GB a day.

**Comment by johnnymatthews** [comment]
Close due to inactivity.
