### ISSUE TITLE
Add RPC and Faucet pages for Calibration.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#1929]
### Request type

New content

### Describe the issue.

Calibration is a testnet. The other testnets (Hyperspace and Local) have _Get test tokens_ pages, while Calibration does not. Hyperspace also has a listing for third-party RPC nodes, while Calibration does not.

## Tasks

- [x] Create a _Get test tokens_ page for Calibration showing the reader how to use the Calibration faucet.
- [x] Add an RPC listing for Calibration.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
Done https://docs.filecoin.io/smart-contracts/developing-contracts/get-test-tokens
