### ISSUE TITLE
[Request]: General Node Providers landing page?

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#2016]
### Request type

New content

### Describe the issue.

Is it possible to have a general node providers landing page at https://docs.filecoin.io/nodes/node-providers/?

Currently, because Ankr is [1st in the list](https://docs.filecoin.io/nodes/node-providers/ankr/) this gives Ankr unfair advantage in our list of public RPC endpoints.

### Is there any other information we need to know?

All current providers can also be found at https://chainlist.org/chain/314

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnnymatthews** [comment]
What'd be the main goal of having a Node Providers page? Throughout the docs, all lists of companies and projects are in alphabetical order, which is why Ankr is at the top.

**Comment by eshon** [comment]
It looks like you've reorg'd this here: https://docs.filecoin.io/networks/mainnet/rpcs/ which is what I'd expect.

The point of a Node Providers page is to provide equal access to all RPC providers, rather than prioritizing Ankr because they are first. Most users are likely to stop at the 1st RPC provider page.

**Comment by johnnymatthews** [comment]
> Most users are likely to stop at the 1st RPC provider page.

This is a fair point. Can put this _Node providers_ page under _Implementations_. Actually, _Remote node providers_ might be a better name.

## Tasks

- [ ] Create a _Remote node providers_ page under `/nodes/implementations/`
- [ ] Consolidate the content that's currently under `/nodes/node-providers/` into this new page.
    - [ ] Explain what a remote node does.
    - [ ] Benefits
    - [ ] Drawbacks
    - [ ] Link to Mainnet and Calibration RPCs.
