### ISSUE TITLE
Add: Partner integration page 

### ISSUE THREAD

**Issue by longfeiWan9** [filecoin-project/filecoin-docs#2040]
We should have a section on docs to cover all the partner integrations we have so that developers can find the relative resources. 
I am proposing to add a new section for `Advanced`. The proposed structure is: 

**Advanced**
- wFIL
- Bridges: Celer, Axelar
- Oracles: Tellor
- Database: TableLand, Polybase

**Comment by johnnymatthews** [comment]
Yeahp, this seems reasonable. This issue can track the creation of this sub-section, but **not** the creation of the individual pages (wFIL, Bridges, Oracles, etc).

# Tasks

 - [ ] Create **Advanced** sub-section under **Smart-contracts**. 
 - [ ] Add placeholder pages for:
     - [ ] wFIL
     - [ ] Bridges
     - [ ] Oracles
     - [ ] Databases
 - [ ] Set the above pages to draft. 
 - [ ] Hide the sub-section from `production` until content exists in the above pages.
