### ISSUE TITLE
Explain how users can inject custom logic into their consideration of storage and retrieval deals.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#243]
The [Support external deal decision logic #2714](https://github.com/filecoin-project/lotus/pull/2714/) PR allows users to run scripts _before_ a storage or retrieval deal is made. These scripts could be stored on a pre-hook server.

## Tasks

- [ ] Explain why users might want to inject custom logic.
- [ ] How to set up a pre-hook server.
- [ ] Issues and/or security concerns with this process.

**Comment by johnnymatthews** [comment]
This issue likely needs input from the Lotus dev team.

**Comment by johndmulhausen** [comment]
Done here: https://docs.filecoin.io/mine/lotus/miner-configuration/#using-filters-for-fine-grained-storage-and-retrieval-deal-acceptance
