### ISSUE TITLE
Create a '"quick start" tutorial for new Filecoin developers.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#251]
The example tutorials we have a good, but they assume that the reader has a decent understanding on Filecoin, blockchain, and crypto already. We need a _quick start_ guide that is simple enough that a regular web developer could read through it and at the end understand what Filecoin is, why it's important, and how they can use it in their projects.

## Tasks

- [ ] Decide what we want to teach the reader.
- [ ] Using the point above, decide what the user should create.
- [ ] Create a _rough_ draft of a tutorial.
- [ ] Clean up the tutorial and run some user testing (give it to someone and see if they have any idea what's going on).

We can go from there.

**Comment by johnnymatthews** [comment]
Started work in #620. Gonna close this in favour of that issue.
