### ISSUE TITLE
Remove the Spacerace page and add a Slingshot page.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#437]
The Spacerace is over! We should remove the page from the sidebar, but keep the actual content around in case folks need to reference it, at least for a little while.

At the same time, we need a page for the Slingshot competition. Most of the content can be grabbed from [slingshot.filecoin.io](https://slingshot.filecoin.io/)

## Tasks

- [ ] Remove the Spacerace item from the sidebar menu.
- [ ] Create a Slingshot page.
    - [ ] What the competition is.
    - [ ] The rules.
    - [ ] How long it's gonna last for.
    - [ ] Judging criteria.
    - [ ] Other stuff that I might have missed.
