### ISSUE TITLE
Add a "Get started" page in the "Build" section.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#620]
Readers need something they can quickly jump into so they can start building on the Filecoin network. The Infura API pairs really well with this, since users don't need to set up their own node or sync anything just to get started.

## Tasks

- [x] Create a simple Node.js script that checks if a string is a valid Filecoin address, and then checks the balance of that address.
- [ ] Make a step-by-step guide in `build/infura`:
    - [ ] Explain what Infura is.
    - [ ] How to sign up to the Infura API.
    - [ ] How to create create the script.
    - [ ] Possible expansions to the script.
- [ ] Grammar and spell check the guide.
