### ISSUE TITLE
[DOCS ISSUE] Page: Lotus: chain management

### ISSUE THREAD

**Issue by shawnp0wers** [filecoin-project/filecoin-docs#622]
Did you find a bug, typo or other issue in an item of Filecoin documentation? Please use this template to let us know!

**URL of the page in question:**
_e.g. https://docs.filecoin.io/introduction/usage/_

**What's wrong with this page?**
The order is wrong with the options for halting after importing the chain. 

**What would you like to have changed/amended/fixed in order to make things right?**
Change the example to:
`lotus daemon --halt-after-import --import-snapshot <filename>`
(it currently has --halt-after-import and --import-snapshot in the wrong order)

**Would you be interested in helping fix this page?**
I don't know how yet, sorry. Eventually I'll figure it out. :) 

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by johnnymatthews** [comment]
Thanks for flagging this issue @shawnp0wers!

> I don't know how yet, sorry. Eventually I'll figure it out. :) 
> \- @shawnp0wers 

There's a super quick tutorial/guide you can follow that walks you throw [how to contribute to the docs](https://docs.filecoin.io/community/contribute/contribution-tutorial), if you'd like to contribute at some point in the future :)

**Comment by johnnymatthews** [comment]
## Tasks

- [ ] Change `lotus daemon --import-snapshot --halt-after-import <filename>` to `lotus daemon --halt-after-import --import-snapshot <filename>`
- [ ] Run command to make sure everything works fine.
- [ ] Paste the output of the command in this thread, so we can ensure the correct command is in there.
