### ISSUE TITLE
A more discoverable recommended Wallets info page for regular users

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-docs#636]
it's not easy for someone on the Internet to figure out which Filecoin wallets are security audited and therefore most recommended. A search for wallets in the Filecoin Docs also mostly lead to Lotus which is harder for non-technical users to set up.

**Ask:** We could make a new Filecoin Wallets page in the docs and link to the Ledger HW + Glif wallets to help make them more discoverable from the main Docs entrypoint.

Resources:
- https://github.com/filecoin-project/venus-docs/wiki#5-wallets
- https://www.reddit.com/r/filecoin/comments/ktvfj8/filfox_wallet/gj01ms7/

**Comment by johnnymatthews** [comment]
There's a section that lists a few wallets, although it's not particularly detailed: https://docs.filecoin.io/get-started/#wallets

We could add more wallets into that section. Or do you think that it would be more beneficial to give wallets a separate section @eshon?

**Comment by eshon** [comment]
@johnnymatthews - that section is not easily discoverable from the Searchbar - how can we ramp up the SEO - in this Search + on the Internet?

**Comment by johnnymatthews** [comment]
That's fair. Creating a new page specifically for wallets, and FIL in general, will probably help things quite a bit.

## Tasks

- [ ] Create new **Wallets** page. This can likely go either into **Get Started** or **About Filecoin**.
- [ ] List available wallets for FIL users [from here](https://github.com/filecoin-project/filecoin-docs/wiki#5-wallets).
- [ ] Move over information already in [`docs.filecoin.io/get-started/#wallets`](https://docs.filecoin.io/get-started/#wallets)

That should do, right @eshon?

**Comment by eshon** [comment]
Looks good @johnnymatthews!

May be less confusing to keep the 'Other Wallets' out of the doc for now and we can put them on big list of Tools page elsewhere. This list will keep growing too and we have to chase them all down and evaluate if they're secure.

**Comment by johnnymatthews** [comment]
Good call. 

Something else to consider; not sure what we're allowed to say in regards to exchanges. I've seen a few messages from folks asking how to buy Filecoin. Most folks need to head to an exchange, and we should say that in the docs. _But_, we probably shouldn't list any exchanges.

**Comment by eshon** [comment]
Yeah, I don't recommend listing any specific exchanges.

But hey, look at this: https://ethereum.org/en/contributing/adding-exchanges/  (they're also linking DeFi ones)

cc: @ianjdarrow

**Comment by johnnymatthews** [comment]
Oh wow, that's pretty handy. It'd be nice to see something like that in these docs, but is out of scope for this issue. I'll make a separate issue for that.
