### ISSUE TITLE
Update the Lotus install instructions for Debian 10.

### ISSUE THREAD

**Issue by vmx** [filecoin-project/filecoin-docs#694]
**URL of the page in question:**
https://docs.filecoin.io/get-started/lotus/installation/#software-dependencies

**What's wrong with this page?**
Installation instructions for Debian 10 might be outdated. See https://github.com/filecoin-project/rust-fil-proofs/discussions/1415 for a user report. It looks like `nvidia-opencl-icd` should be installed when you have an nvidia card.

**What would you like to have changed/amended/fixed in order to make things right?**
The installation should be followed on a Debian 10 and check if the error the user saw can be reproduced. If not, then perhaps it makes sense to add the users issue to some trouble shooting question. `ClError(BusIdNotAvailable)` in the error message kind of indicates that there's something wrong with the drivers.

**Would you be interested in helping fix this page?**
No.

**Comment by johnnymatthews** [comment]
## Tasks

- [ ] Spin up a vanilla Debian 10 machine with an Nvidia graphics card installed.
    - [ ] Grab the vanilla ISO from the Debian website: https://www.debian.org/
- [ ] Install all listed dependencies, including the above `nvidia-opencl-icd`.
- [ ] Attempt an install of Lotus.
- [ ] If Lotus installs correctly, add `nvidia-opencl-icd` to the [software dependencies section](https://docs.filecoin.io/get-started/lotus/installation/#software-dependencies).
    - [ ] If the Lotus install fails, return to this thread to discuss possible reasons. Bring in further engineers from the Lotus team if necessary.

**Comment by chuck-r** [comment]
I did a lot of work in researching this issue, but I found a workaround. I tried my best to keep it coherent, but I'm sorry if it comes off a little rambly.

This will also happen if you have multiple ICD's installed. I had `opencl-mesa` (Manjaro/Arch package) installed as well as `opencl-amd` (from AUR, which comes with the AMDGPU-PRO ICD's) installed. It should be noted that the Mesa OpenCL implementation is not functional on my configuration, so although it was present, it didn't work. For some reason, both `lotus` and `lotus-benchmark` would fail like this:

> 2021-07-12T00:01:41.814-0500	INFO	lotus-bench	lotus-bench/main.go:526	[0] Writing piece into sector...
> 2021-07-12T00:01:41.815 TRACE filecoin_proofs::api > generate_piece_commitment:start
> 2021-07-12T00:01:41.816 TRACE filecoin_proofs::api > generate_piece_commitment:finish
> 2021-07-12T00:01:41.820-0500	INFO	lotus-bench	lotus-bench/main.go:562	[0] Running replication(1)...
> 2021-07-12T00:01:41.820 INFO filcrypto::proofs::api > seal_pre_commit_phase1: start
> 2021-07-12T00:01:41.820 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:start: SectorId(0)
> 2021-07-12T00:01:41.821 INFO filecoin_proofs::api::seal > building merkle tree for the original data
> 2021-07-12T00:01:41.821 TRACE filecoin_proofs::api::seal > seal phase 1: sector_size 2048, base tree size 127, base tree leafs 64
> 2021-07-12T00:01:41.821 TRACE storage_proofs_core::merkle::builders > create_merkle_tree called with size 64
> 2021-07-12T00:01:41.821 TRACE storage_proofs_core::merkle::builders > is_merkle_tree_size_valid(64, arity 2) = true
> 2021-07-12T00:01:41.823 INFO filecoin_proofs::api::seal > verifying pieces
> 2021-07-12T00:01:41.823 INFO filecoin_proofs::pieces > verifying 1 pieces
> 2021-07-12T00:01:41.823 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase1
> 2021-07-12T00:01:41.823 INFO storage_proofs_porep::stacked::vanilla::graph > using parent_cache[64 / 64]
> 2021-07-12T00:01:41.823 INFO storage_proofs_porep::stacked::vanilla::cache > parent cache: opening /media/FileCoin/proofs/.filproofsfilecoin-parents/v28-sdr-parent-494d91dc80f2df5272c4b9e129bc7ade9405225993af9fe34e6542a39a47554b.cache, verify enabled: false
> 2021-07-12T00:01:41.823 INFO storage_proofs_porep::stacked::vanilla::proof > single core replication
> 2021-07-12T00:01:41.823 INFO storage_proofs_porep::stacked::vanilla::create_label::single > generate labels
> 2021-07-12T00:01:41.823 INFO storage_proofs_porep::stacked::vanilla::create_label::single > generating layer: 1
> 2021-07-12T00:01:41.823 INFO storage_proofs_porep::stacked::vanilla::create_label::single >   storing labels on disk
> 2021-07-12T00:01:41.824 INFO storage_proofs_porep::stacked::vanilla::create_label::single >   generated layer 1 store with id layer-1
> 2021-07-12T00:01:41.824 INFO storage_proofs_porep::stacked::vanilla::create_label::single >   setting exp parents
> 2021-07-12T00:01:41.824 INFO storage_proofs_porep::stacked::vanilla::create_label::single > generating layer: 2
> 2021-07-12T00:01:41.824 INFO storage_proofs_porep::stacked::vanilla::create_label::single >   storing labels on disk
> 2021-07-12T00:01:41.824 INFO storage_proofs_porep::stacked::vanilla::create_label::single >   generated layer 2 store with id layer-2
> 2021-07-12T00:01:41.824 INFO storage_proofs_porep::stacked::vanilla::create_label::single >   setting exp parents
> 2021-07-12T00:01:41.824 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:finish: SectorId(0)
> 2021-07-12T00:01:41.824 INFO filcrypto::proofs::api > seal_pre_commit_phase1: finish
> 2021-07-12T00:01:41.824-0500	INFO	lotus-bench	lotus-bench/main.go:573	[0] Running replication(2)...
> 2021-07-12T00:01:41.824 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
> 2021-07-12T00:01:41.824 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
> 2021-07-12T00:01:41.824 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:finish
> 2021-07-12T00:01:41.824 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:start
> 2021-07-12T00:01:41.824 TRACE filecoin_proofs::api::seal > seal phase 2: base tree size 127, base tree leafs 64, rows to discard 5
> 2021-07-12T00:01:41.824 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
> 2021-07-12T00:01:41.824 TRACE storage_proofs_porep::stacked::vanilla::proof > transform_and_replicate_layers
> 2021-07-12T00:01:41.824 TRACE storage_proofs_porep::stacked::vanilla::proof > nodes count 64, data len 2048
> 2021-07-12T00:01:41.824 TRACE storage_proofs_porep::stacked::vanilla::proof > is_merkle_tree_size_valid(64, BINARY_ARITY) = true
> 2021-07-12T00:01:41.824 TRACE storage_proofs_porep::stacked::vanilla::proof > is_merkle_tree_size_valid(64, 8) = true
> 2021-07-12T00:01:41.824 TRACE storage_proofs_porep::stacked::vanilla::proof > tree_r_last using rows_to_discard=1
> 2021-07-12T00:01:41.824 INFO storage_proofs_porep::stacked::vanilla::proof > Building trees [524288 descriptors max available]
> 2021-07-12T00:01:41.824 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU
> 2021-07-12T00:01:41.824 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
> 2021-07-12T00:01:41.824 TRACE storage_proofs_porep::stacked::vanilla::proof > processing config 1/1 with column nodes 64
> 2021-07-12T00:01:41.824 TRACE storage_proofs_porep::stacked::vanilla::proof > node index 64/64/64
> 2021-07-12T00:01:41.880 DEBUG rust_gpu_tools::opencl::utils > loaded devices: {Amd: []}
> thread '<unnamed>' panicked at 'failed to create ColumnTreeBuilder: ClError(BusIdNotAvailable)', /home/chuck/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-8.0.2/src/stacked/vanilla/proof.rs:596:22
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'failed to send columns: SendError { .. }failed to receive base_data, tree_data for tree_c: RecvError', ', /home/chuck/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-8.0.2/src/stacked/vanilla/proof.rs/home/chuck/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-8.0.2/src/stacked/vanilla/proof.rs::584641::3426
> 
> 2021-07-12T00:01:41.881-0500	WARN	lotus-bench	lotus-bench/main.go:115	failed to run seals:
>     main.glob..func3
>         /home/chuck/git/lotus/cmd/lotus-bench/main.go:274
>   - commit:
>     main.runSeals.func1.1
>         /home/chuck/git/lotus/cmd/lotus-bench/main.go:576
>   - presealing sector 0 ():
>     github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
>         /home/chuck/git/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:530
>   - Rust panic: no unwind information
>     github.com/filecoin-project/filecoin-ffi.SealPreCommitPhase2
>     	/home/chuck/git/lotus/extern/filecoin-ffi/proofs.go:376
>     github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
>     	/home/chuck/git/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:528
>     main.runSeals.func1.1
>     	/home/chuck/git/lotus/cmd/lotus-bench/main.go:574
>     main.runSeals.func1
>     	/home/chuck/git/lotus/cmd/lotus-bench/main.go:685
>     runtime.goexit
>     	/usr/lib/go/src/runtime/asm_amd64.s:1371

Odldy, this same error would occur when using `lotus-bench seal --no-gpu`

In my case, I am using an Radeon RX 6800 XT, so I had to set `BELLMAN_CUSTOM_GPU="gfx1030:4608"`*. From what I could gather, it looks like lotus/lotus-benchmark is only pulling from the first OpenCL Platform (which in my case was Mesa and not AMD), not finding the card specified in `BELLMAN_CUSTOM_GPU`, and failing with a very unhelpful error. Or, it was seeing a valid OpenCL implementation through Mesa (and my GPU was listed in it, though not as "gfx1030") and using the first card available which just so happened to be non-functional on the RX 6800 XT.

The correct behavior should be for it to try every platform for a card matching the given OpenCL name first and, if not found, then maybe gracefully fail and retry another Platform:Device combo until they all fail before a panic. Or, at the very least, if `BELLMAN_CUSTOM_GPU` is specified it should notify the user that the device wasn't found (and probably which platform it was searching) or something more helpful.

I looked a the source of filecoin-project/fil-ocl and noticed a mention of an environment variable called `OCL_DEFAULT_PLATFORM_IDX`. This is a zero-based index for the Platform number found in, i.e., `clinfo`. Once I set `OCL_DEFAULT_PLATFORM_IDX=1` ("AMD Accelerated Parallel Processing" -- the working OpenCL implementation for my card was the second in the list given by `clinfo` prior to removing mesa-opencl) it started working. After removing `mesa-opencl`, it works without workarounds. I can think of one circumstance that removing all other ICD's would not be practical: an Intel CPU with a NVIDIA/AMD graphics card. There may be a valid reason to have two ICD's/Platforms installed.

* I'm pretty sure I'm not the first to get the RX 6800 XT working in FileCoin, but I have found no other information about how to set up the card. I have been flying blind and managed to get it working in benchmarking 512MiB sectors, but I'm going to test it in production very soon (read: after I finish this post).
