### ISSUE TITLE
[CONTENT REQUEST] Uninstall Instructions

### ISSUE THREAD

**Issue by kingstonstation** [filecoin-project/filecoin-docs#701]
Is there an item missing from Filecoin documentation that would be helpful to you? Please use this template to let us know!

**What's the subject of the item you're requesting?**
Step-by-step uninstallation instructions

**What's the content of the item you're requesting?**
It's entirely possible that the installation instructions are easily reverse-engineered by someone familiar with line-commands.  But, for someone who's a relative newbie to line-commands, it's difficult (if not impossible) to extrapolate an "uninstall" procedure from the installation procedure.

**What will the user know how to do after going through this item?**
How to do a complete, clean install including the ~22Gb snapshot chain file.

**Would you be interested in helping create this item?**
I don't know how.

**Is there any other feedback you'd like to share about Filecoin docs?**

**Comment by johnnymatthews** [comment]
You make a fair point @kingstonstation. These docs are fairly easy to produce by someone familiar to the project. The process isn't as simple as double-clicking an `Uninstall.exe` however, and is mostly going into various directories and removing files/folders. Luckily, the uninstall process some the similar, if not the same, across operating systems.

## Tasks

- [ ] Install Lotus on a completely clean VM.
- [ ] Set up a Lotus miner on the system.
- [ ] Leave things running for a couple of days to get a realistic amount of data/storage into the system (this may be overkill, however).
- [ ] Remove everything surrounding Lotus from the VM.
    - [ ] ~/.lotus
    - [ ] ~/.lotusminer
    - [ ] Any Lotus repos
    - [ ] Lotus commands from places like ~/.bashrc
    - [ ] Any other `export` values from installing Lotus.
