### ISSUE TITLE
[DOCS ISSUE] Page: Why Filecoin?

### ISSUE THREAD

**Issue by dacoach01** [filecoin-project/filecoin-docs#738]
**URL of the page in question:**
https://docs.filecoin.io/about-filecoin/why-filecoin/

**What's wrong with this page?**
This page explains nicely how the miners responsibilities are established and incentivized for reliability, and punished for poor reliability, but it doesn't explain what happens to the contents of the stored data if said miner acts irresponsibly and loses the content they store.  How is the consumer of the storage affected?

**What would you like to have changed/amended/fixed in order to make things right?**
Explain if there is redundancy of data distributed in the "swarm" of retrieving class or the storing class.  If joe blow network participant just shuts down, where does the data go from that node?  How is it retrieved if lost or destroyed?

**Would you be interested in helping fix this page?**
No. Just trying to learn and not getting some basic info from the site.

**Is there any other feedback you'd like to share about Filecoin docs?**
No.

**Comment by johnnymatthews** [comment]
This is a good point.

## Tasks

- [ ] Review how miners are punished.
- [ ] Explain how this affects client-data.
- [ ] Explain how clients can protect themselves from losing access to data due to an unreliable miner.

This can likely go into the [How Filecoin Works](https://docs.filecoin.io/about-filecoin/how-filecoin-works/#deals) page.
