### ISSUE TITLE
Add `api.chain.love` to `/build/lotus/lotus-lite`.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#838]
Since we're using the `api.chain.love` node for pretty much everything these days, we should add it into `docs/build/lotus/lotus-lite`. Currently we require to reader to already have a full-node IP address ready.

## Tasks

- [ ] Replace any full-node IP addresses with `api.chain.love`.
- [ ] Explain what `api.chain.love` is
    - [ ] A full-node managed by PL.
    - [ ] Free to use.
    - [ ] Probably shouldn't use it for production stuff though.

**Comment by f8-ptrk** [comment]
maybe even document `api.chain.love` itself? 

i see it the first time....

**Comment by placer14** [comment]
There seems to be a blurb about this at https://docs.filecoin.io/build/lotus/lotus-lite/#full-node-preparation. Maybe this is solved?

**Comment by johnnymatthews** [comment]
This is indeed solved.
