### ISSUE TITLE
https://docs.filecoin.io/get-started/lotus/installation/#build-and-install-lotus

### ISSUE THREAD

**Issue by f8-ptrk** [filecoin-project/filecoin-docs#868]
with the new branch system for lotus we see a fair amount of miners checking out master instead of the latest release tag.

is there a way to dynamically pull the latest stable release tag from filecoin-project/lotus and replace the <x.x.x> with it in the build instructions?

having people on 1.11-dev instead of 1.9.0 is causing possible problems for them

**Comment by johnnymatthews** [comment]
> is there a way to dynamically pull the latest stable release tag from filecoin-project/lotus

As far as I know, no, there isn't a way to grab that directly from GitHub. Saying that, we're going to start relying on the pre-built binaries for the majority of the docs. Having people run a select binary instead of building their own from one of multiple branches should make things a bit easier for everyone.

To answer this issue though, when we do tell readers to build their own binary, we should tell them to view the latest tagged release in the `lotus/releases` page, and use that.

**Comment by f8-ptrk** [comment]
when i build a AMD binary on a Threadripper ubuntu and then tryto dun it on a debian 10 7002 rome AMD - it will fail. keep that in mind that those are not portable between, at least distros, maybe not even CPU architectures

**Comment by johnnymatthews** [comment]
Yeah; so that issue stems from the fact that Debian and Ubuntu put their dependencies in different locations. So, the `libhwloc` dep will be in completely different places between Debian and Ubuntu, which makes the pre-build binaries somewhat useless. However, we're building AppImages into the build cycle for Lotus, so users like yourself will be able to run that as a stand alone executable.

Anyway, here's the tasks for this particular issue:

## Tasks

- [ ] Write steps to:
    - [ ] How to check out Lotus to a particular tag.
    - [ ] How to view all the available tags.

**Comment by mishmosh** [comment]
Yeah, constant pain point. Looks like #899 starts to address this, though networks.filecoin.io doesn't show all the different tags for different architectures. Where to view those details?

**Comment by f8-ptrk** [comment]
@johnnymatthews AppImages are somewhat exactly what we won't run. i'd rather build 50 binaries on my own so run it on the shmoggiest calculator i have lying around then running an AppImage on a production system :P

in case of security issues AppImages tend to be the last thing people replace, maybe it needs an auto update mechanism for them

**Comment by johnnymatthews** [comment]
> doesn't show all the different tags for different architectures. Where to view those details? - @mishmosh 

The only place I know of to find those tags is GitHub, annoyingly. Wonder if there's a way to automate grabbing them though?

> AppImages are somewhat exactly what we won't run.

Yeah, so AppImages are mainly for devs and end-users, not miners.
