### ISSUE TITLE
Review Lotus Snapcraft page.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#891]
There is now a [page for Lotus on Snapcraft](https://snapcraft.io/lotus-filecoin)! It just needs a quick review to tidy things up a bit.

## Tasks

- [x] Explain (quickly) what Filecoin is.
- [x] Explain what Lotus is.
- [x] Add relevant links to:
    - [x] Filecoin homepage
    - [x] Filecoin docs
    - [x] Filecoin foundation
    - [x] Lotus source (on GitHub).

**Comment by johnnymatthews** [comment]
> Filecoin is a peer-to-peer network that stores files on the internet with built-in economic incentives to ensure files are stored reliably over time. Lotus is the reference implementation for Filecoin, and is the main client used for mining and interacting with the network.
> 
> - [Filecoin.io](https://filecoin.io)
> - [The Filecoin Foundation](https://fil.org)
> - [Documentation](https://docs.filecoin.io)
> - [Lotus source code](https://github.com/filecoin-project/lotus)

**Comment by johnnymatthews** [comment]
Sent request to Infra to change the Snapcraft page to the comment above. Closing.
