### ISSUE TITLE
Explain how to use AppImages for Lotus

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/filecoin-docs#892]
PR #881 has already started this one.

## Tasks

- [x] Quickly explain what AppImages are (self-contained executables that run on their own with all the deps).
- [x] What OSes AppImages run on.
- [x] Limitations of AppImages (probably shouldn't be used for miners since they need _very_ optimized settings).
- [x] How to grab the latest Lotus AppImage.
